# Generated by Django 4.0.4 on 2022-05-05 13:35

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Lessons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votes',
            name='video_lesson',
        ),
        migrations.RemoveField(
            model_name='votes',
            name='visits',
        ),
        migrations.AddField(
            model_name='category',
            name='url',
            field=models.URLField(default=1, verbose_name='Ссылка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='country',
            field=django_countries.fields.CountryField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='url',
            field=models.URLField(default=1, verbose_name='Ссылка'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Votes',
        ),
    ]
